// <auto-generated />
using System;
using Ag.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Ag.Domain.Migrations
{
    [DbContext(typeof(AgDbContext))]
    partial class AgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Ag.Domain.Models.IncomeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<double>("IncomeInDollars");

                    b.Property<int>("OperatorId");

                    b.Property<int>("PerformerId");

                    b.Property<string>("SiteName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PerformerId");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("Ag.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ColleagueId");

                    b.Property<double>("MaxPercent");

                    b.Property<double>("MinPercent");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<int>("Role");

                    b.Property<int>("Shift");

                    b.Property<string>("Sites");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ColleagueId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ag.Domain.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("OperatorId");

                    b.Property<int>("PerformerId");

                    b.Property<int>("Shift");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PerformerId");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("Ag.Domain.Models.IncomeEntry", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Operator")
                        .WithMany("OperatorIncomeEntries")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ag.Domain.Models.User", "Performer")
                        .WithMany("PerformerIncomeEntries")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ag.Domain.Models.User", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Colleague")
                        .WithMany()
                        .HasForeignKey("ColleagueId");
                });

            modelBuilder.Entity("Ag.Domain.Models.WorkDay", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Operator")
                        .WithMany("OperatorWorkDays")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ag.Domain.Models.User", "Performer")
                        .WithMany("PerformerWorkDays")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
