// <auto-generated />
using System;
using Ag.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Ag.Domain.Migrations
{
    [DbContext(typeof(AgDbContext))]
    partial class AgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Ag.Domain.Models.IncomeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IncomeEntryId");

                    b.Property<double>("IncomeForOperator");

                    b.Property<double>("IncomeForPerformer");

                    b.Property<double>("IncomeForStudio");

                    b.Property<int>("Site");

                    b.Property<double>("Sum");

                    b.HasKey("Id");

                    b.HasIndex("IncomeEntryId");

                    b.ToTable("IncomeChunks");
                });

            modelBuilder.Entity("Ag.Domain.Models.IncomeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Locked");

                    b.Property<int>("OperatorId");

                    b.Property<int>("PerformerId");

                    b.Property<double>("TotalIncomeForOperator");

                    b.Property<double>("TotalIncomeForPerformer");

                    b.Property<double>("TotalIncomeForStudio");

                    b.Property<double>("TotalSum");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PerformerId");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("Ag.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ColleagueId");

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<double>("MaxPercent");

                    b.Property<double>("MinPercent");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<int>("Role");

                    b.Property<int>("Shift");

                    b.Property<string>("Sites")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ColleagueId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ag.Domain.Models.UserRelation", b =>
                {
                    b.Property<int>("FromId");

                    b.Property<int>("ToId");

                    b.HasKey("FromId", "ToId");

                    b.HasIndex("ToId");

                    b.ToTable("UserRelations");
                });

            modelBuilder.Entity("Ag.Domain.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("OperatorId");

                    b.Property<int>("PerformerId");

                    b.Property<int>("Shift");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PerformerId");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("Ag.Domain.Models.IncomeChunk", b =>
                {
                    b.HasOne("Ag.Domain.Models.IncomeEntry", "IncomeEntry")
                        .WithMany("IncomeChunks")
                        .HasForeignKey("IncomeEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ag.Domain.Models.IncomeEntry", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ag.Domain.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ag.Domain.Models.User", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Colleague")
                        .WithMany()
                        .HasForeignKey("ColleagueId");
                });

            modelBuilder.Entity("Ag.Domain.Models.UserRelation", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "UserFrom")
                        .WithMany("RelatedTo")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ag.Domain.Models.User", "UserTo")
                        .WithMany("RelatedFrom")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ag.Domain.Models.WorkDay", b =>
                {
                    b.HasOne("Ag.Domain.Models.User", "Operator")
                        .WithMany("OperatorWorkDays")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ag.Domain.Models.User", "Performer")
                        .WithMany("PerformerWorkDays")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
